### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by mvolkmann** [domingues/svelte-ssr-example#3]
I want to learn about implementing SSR in Svelte.
I'm assuming most of the magic is in rollup.config.js.
Did you have to do anything in other files to get SSR working?

**Comment by domingues** [comment]
The `rollup.config.js` will _compile_ the three parts needed to run the example:

- Svelte client side code, css, assets and a file with the dependency tree (`dist/client-tree.json`): https://github.com/domingues/svelte-ssr-example/blob/2fe9ae73757b68056723f1c321c0a1d6053ff66f/rollup.config.js#L18-L58
- Svelte server side code: https://github.com/domingues/svelte-ssr-example/blob/2fe9ae73757b68056723f1c321c0a1d6053ff66f/rollup.config.js#L59-L85
- HTTP server (`src/server.js`) to glue the first two parts: https://github.com/domingues/svelte-ssr-example/blob/2fe9ae73757b68056723f1c321c0a1d6053ff66f/rollup.config.js#L86-L106

When running the HTTP server will:

1. Load the requested Svelte component: https://github.com/domingues/svelte-ssr-example/blob/2fe9ae73757b68056723f1c321c0a1d6053ff66f/src/server.js#L73-L79
2. Render the component with the given properties: https://github.com/domingues/svelte-ssr-example/blob/2fe9ae73757b68056723f1c321c0a1d6053ff66f/src/server.js#L85-L91
3. Get component client side dependencies: https://github.com/domingues/svelte-ssr-example/blob/2fe9ae73757b68056723f1c321c0a1d6053ff66f/src/server.js#L93-L98
4. Generated the HTML output: https://github.com/domingues/svelte-ssr-example/blob/2fe9ae73757b68056723f1c321c0a1d6053ff66f/src/server.js#L99-L102

**Comment by mvolkmann** [comment]
Thanks so much for the detailed answer!
